
app = 'marketing-analytics-server'
primary_region = 'bom'

[processes]
web = "./marketing-analytics-server"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ["web"]
[http_service.concurrency]
hard_limit = 2000
soft_limit = 500

[env]
BACKEND = "LIVE"
RUST_LOG = "info"
SERVER_PORT = "3000"
IP_DB_PATH = "/app/ip_db.mmdb"


[[vm]]
memory = '4gb'
cpu_kind = 'shared'
cpus = 4