
app = 'marketing-analytics-server'
primary_region = 'bom'

[processes]
web = "./marketing-analytics-server"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "off"
auto_start_machines = false
min_machines_running = 1
processes = ["app"]

[env]
BACKEND = "LIVE"
RUST_LOG = "info"
SERVER_PORT = "3000"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
