
app = 'marketing-analytics-server'
primary_region = 'bom'

[processes]
web = "./marketing-analytics-server"

[[services]]
internal_port = 3000
protocol = "tcp"
processes = ["web"]
http_checks = []

[[services.ports]]
handlers = ["tls", "http"] 
tls_options = { "versions" = ["TLSv1.2", "TLSv1.3"] } 
port = 443

[env]
BACKEND = "LIVE"
RUST_LOG="info"
SERVER_PORT="3000"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
