name: Fly Deploy

on:
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group  

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      # Set secrets before deploying
      - name: Set Fly secrets
        run: |
          flyctl secrets set SERVER_ACCESS_TOKEN=$SERVER_ACCESS_TOKEN --app "marketing-analytics-server" --stage
          flyctl secrets set MIXPANEL_PROJECT_TOKEN=$MIXPANEL_PROJECT_TOKEN --app "marketing-analytics-server" --stage
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
          SERVER_ACCESS_TOKEN: ${{ secrets.SERVER_ACCESS_TOKEN }}
          MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}

          
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
