name: Fly Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Set secrets before deploying
      - name: Set Fly secrets
        run: |
          flyctl secrets set SERVER_ACCESS_TOKEN=$SERVER_ACCESS_TOKEN --app "marketing-analytics-server-staging" --stage
          flyctl secrets set MIXPANEL_PROJECT_TOKEN=$MIXPANEL_PROJECT_TOKEN --app "marketing-analytics-server-staging" --stage
          flyctl secrets set GOOGLE_SA_KEY=$GOOGLE_SA_KEY --app "marketing-analytics-server-staging" --stage
          flyctl secrets set SENTRY_GOOGLE_CHAT_WEBHOOK_URL=$SENTRY_GOOGLE_CHAT_WEBHOOK_URL --app "marketing-analytics-server-staging" --stage
          flyctl secrets set SENTRY_CLIENT_SECRET=$SENTRY_CLIENT_SECRET --app "marketing-analytics-server-staging" --stage
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
          SERVER_ACCESS_TOKEN: ${{ secrets.SERVER_ACCESS_TOKEN }}
          MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
          GOOGLE_SA_KEY: ${{ secrets.GOOGLE_SA_KEY }}
          SENTRY_GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.SENTRY_GOOGLE_CHAT_WEBHOOK_URL }}
          SENTRY_CLIENT_SECRET: ${{ secrets.SENTRY_CLIENT_SECRET }}

      - name: Deploy to Fly
        run: flyctl deploy --remote-only -c fly-staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
